<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<UseWindowsForms>true</UseWindowsForms>
		<RootNamespace>04-InitDirect3D</RootNamespace>
		<TargetFramework>net8.0-windows</TargetFramework>
	</PropertyGroup>
	<ItemGroup>
	  <PackageReference Include="SharpDX" Version="4.0.1" />
	  <PackageReference Include="SharpDX.D3DCompiler" Version="4.0.1" />
	  <PackageReference Include="SharpDX.Direct3D12" Version="4.0.1" />
	  <PackageReference Include="SharpDX.DXGI" Version="4.0.1" />
	  <PackageReference Include="SharpDX.Mathematics" Version="4.0.1" />
	</ItemGroup>
	<ItemGroup>
	  <Content Include="Shaders\pixel.hlsl">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Shaders\vertex.hlsl">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>
</Project>