<Project Sdk="Microsoft.NET.Sdk">


  <PropertyGroup>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>CatGen</RootNamespace>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

    <ItemGroup>
      <Compile Update="EditorForm.cs">
        <SubType>Form</SubType>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CatGen.Interfaces\CatGen.Interfaces.csproj" />
    </ItemGroup>

</Project>
