// <auto-generated />
using CatGen.Saves;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatGen.Saves.Migrations
{
    [DbContext(typeof(SaveContext))]
    partial class SaveContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("CatGen.DTOs.ModelOnDisk", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ModelsOnDisk");
                });

            modelBuilder.Entity("CatGen.DTOs.SpawnedObject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelOnDiskId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("X")
                        .HasColumnType("REAL");

                    b.Property<float>("Y")
                        .HasColumnType("REAL");

                    b.Property<float>("Z")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ModelOnDiskId");

                    b.ToTable("SpawnedObjects");
                });

            modelBuilder.Entity("CatGen.DTOs.SpawnedObject", b =>
                {
                    b.HasOne("CatGen.DTOs.ModelOnDisk", null)
                        .WithMany("SpawnedObjects")
                        .HasForeignKey("ModelOnDiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CatGen.DTOs.ModelOnDisk", b =>
                {
                    b.Navigation("SpawnedObjects");
                });
#pragma warning restore 612, 618
        }
    }
}
